name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest
    timeout-minutes: 20 

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /var/www/html/dogebark/app
            git pull origin main
            git status
            yarn install
            yarn build
            pm2 reload barktest
            pm2 restart barktest
            pm2 stop barktest
            pm2 start barktest
